<tr>
    <td colspan="5">
        <div class="section-config">
            <div class="entry-edit-head admin__collapsible-block">
                <?= /* @noEscape */ __('Click link / Navigate path below to configure Catalog Price Scope') ?>
                <a href="<?= /* @noEscape */ $block->getUrl('adminhtml/system_config/edit/section/catalog') ?>" title="Manage Catalog Price Settings">
                    <?= /* @noEscape */ __('STORES > Configuration > CATALOG > Catalog > Price') ?>
                </a>
            </div>
        </div>
    </td>
</tr>
