<div style="padding:12px;">
    <div>
        <p>
            <strong><?= /* @noEscape */ __('AUTHOR : ') ?></strong>
            <a target="_blank" href="https://github.com/mdbhojwani" title="Manish Bhojwani - GitHub Profile">
                <strong>MANISH BHOJWANI</strong>
            </a>
        </p>
        <p>
            <?= /* @noEscape */ __('Need Support? Contact me on') ?>
            <a href="https://github.com/mdbhojwani" title="Manish Bhojwani - GitHub Profile" target="_blank">
                <?= /* @noEscape */ __('GitHub') ?>
            </a>
            <?= /* @noEscape */ __('|') ?>
            <a href="https://www.linkedin.com/in/manish-bhojwani-01287846/" title="Manish Bhojwani - Linked In Profile" target="_blank">
                <?= /* @noEscape */ __('Linked In') ?>
            </a>
        </p>
    </div>
</div>
