<div style="padding:12px;">
    <div style="padding-left: 11px; font-size: 1.3rem;">
        <p>
            <a target="_blank" href="https://github.com/mdbhojwani" title="Manish Bhojwani - GitHub Profile">
                <strong>MANISH BHOJWANI</strong>
            </a>
        </p>
        <p>
            <?= /* @noEscape */ __('Need Support? Contact us') ?>
            <a href="https://github.com/mdbhojwani" title="Manish Bhojwani - GitHub Profile" target="_blank">
                <?= /* @noEscape */ __('GitHub') ?>
            </a>
            <a href="https://www.linkedin.com/in/manish-bhojwani-01287846/" title="Manish Bhojwani - Linked In Profile" target="_blank">
                <?= /* @noEscape */ __('Linked In') ?>
            </a>
        </p>
    </div>
</div>
